input_shape: [160, 192, 160]
latent_dim: 1
layers: ~

age_dim: 1
bmi_dim: 46
predict_age: no
invariance: no
lr: 0.0004
min_lr: 0.00004
optimizer: 'AdamW'
momentum: 0.9
weight_decay: 0.01
losses_weights:
  reconstruction: 1.0
  prior: 0.00001
  marginal: 0.0
  gender: 1.0
  bmi: 100.0
  age: 0.0