input_shape: [160, 192, 160]
latent_dim: 250
layers:
 conv1:
  channels: 32
  kernel_size: 3
  stride: 2
  padding: 1
  pool_size: 0
  pool_stride: 0
  bias: yes
  batch_norm: yes
  activation: 'relu'
 conv2:
  channels: 64
  kernel_size: 3
  stride: 2
  padding: 1
  pool_size: 0
  pool_stride: 0
  bias: yes
  batch_norm: yes
  activation: 'relu'
 conv3:
  channels: 128
  kernel_size: 3
  stride: 2
  padding: 1
  pool_size: 0
  pool_stride: 0
  bias: yes
  batch_norm: yes
  activation: 'relu'
 conv4:
  channels: 256
  kernel_size: 3
  stride: 2
  padding: 1
  pool_size: 0
  pool_stride: 0
  bias: yes
  batch_norm: yes
  activation: 'relu'
 conv5:
  channels: 256
  kernel_size: 3
  stride: 2
  padding: 1
  pool_size: 0
  pool_stride: 0
  bias: yes
  batch_norm: yes
  activation: 'relu'
 conv6:
  channels: 64
  kernel_size: 1
  stride: 1
  padding: 0
  pool_size: 0
  pool_stride: 0
  bias: yes
  batch_norm: yes
  activation: 'relu'

age_dim: 70
bmi_dim: 46
predict_age: yes
invariant: no
lr: 0.0004
min_lr: 0.00004
optimizer: 'AdamW'
momentum: 0.9
weight_decay: 0.01
losses_weights:
  reconstruction: 1.0
  prior: 0.00001
  marginal: 0.0
  gender: 1.0
  bmi: 1.0
  age: 1.0
