input_shape: [160, 192, 160]
latent_dim: 354
kernel_size: 3
stride: 1
padding: 1
pool_size: 2
pool_stride: 2
last_kernel_size: 1
last_padding: 0
channels: [32, 64, 128, 256, 256, 64]
conditional_dim: 1
lr: 0.1
max_lr: 0.01
optimizer: 'AdamW'
momentum: 0.9
weight_decay: 0.0005
losses_weights:
  reconstruction: 1.0
  prior: 1.0
  marginal: 1.0