input_shape: [56, 64, 56]
latent_dim: 96
layers:
 conv1:
  channels: 32
  kernel_size: 3
  stride: 2
  padding: 1
  pool_size: 0
  pool_stride: 0
  bias: yes
  batch_norm: yes
  activation: 'relu'
 conv2:
  channels: 64
  kernel_size: 3
  stride: 2
  padding: 1
  pool_size: 0
  pool_stride: 0
  bias: yes
  batch_norm: yes
  activation: 'relu'
 conv3:
  channels: 64
  kernel_size: 3
  stride: 2
  padding: 1
  pool_size: 0
  pool_stride: 0
  bias: yes
  batch_norm: yes
  activation: 'relu'

conditional_dim: 0
one_hot_age: no
lr: 0.01
max_lr: 0.01
optimizer: 'AdamW'
momentum: 0.9
weight_decay: 0.0005
losses_weights:
  reconstruction: 1.0
  prior: 1.0
  marginal: 0.0
